# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 672b0617d3d2e11e44b92e5c572086523c5e4c34fb19e39b58158175b0dfdef3dfab87f35b7bf62e772739d9c931b3b43076a74364211e81730fc9525cdaab1a

test:
  secret_key_base: 474835520724ed0539fc3ed7d671a35330a90d3765132e7facdeb34b8232201d17a934f7289719228a52877b237b0786aa37620cf2f2bb3da484dbf5b3fce36a


# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
